"use client"
import React, { useEffect, useRef, useState, useCallback } from "react";
import { Activity, GitBranch, Zap, Bug, Users, BarChart3, Terminal as TerminalIcon, ChevronDown, ArrowRight, Github, MessageCircle, BookOpen, Boxes, Radio, ArrowUpRight, Check, Sparkles, Layers } from "lucide-react";
import { AreaChart, Area, LineChart, Line, ResponsiveContainer, XAxis, YAxis, Tooltip } from "recharts";
import Link from "next/link";
function useReveal(threshold = 0.2) { const ref = useRef(null); const [visible, setVisible] = useState(false); useEffect(() => { const node = ref.current; if (!node) return; const obs = new IntersectionObserver((entries) => { entries.forEach((e) => { if (e.isIntersecting) { setVisible(true); obs.unobserve(node); } }); }, { threshold }); obs.observe(node); return () => obs.disconnect(); }, [threshold]); return [ref, visible]; }
function Reveal({ children, delay = 0, className = "", as = "div" }) { const [ref, visible] = useReveal(); const Tag = as; return (<Tag ref={ref} className={`reveal ${visible ? "reveal-in" : ""} ${className}`} style={{ transitionDelay: `${delay}ms` }}>{children}</Tag>); }
function useCountUp(target, duration = 1600, active = false) { const [value, setValue] = useState(0); useEffect(() => { if (!active) return; let start = null; let raf; const step = (ts) => { if (start === null) start = ts; const progress = Math.min((ts - start) / duration, 1); const eased = 1 - Math.pow(1 - progress, 3); setValue(target * eased); if (progress < 1) raf = requestAnimationFrame(step); }; raf = requestAnimationFrame(step); return () => cancelAnimationFrame(raf); }, [active, target, duration]); return value; }
function Logo({ size = 22 }) { return (<span className="tf-logo"><svg width={size} height={size} viewBox="0 0 24 24" fill="none"><path d="M4 12c2 0 2-5 5-5s3 5 5 5 2-5 5-5" stroke="url(#lg1)" strokeWidth="2" strokeLinecap="round"/><path d="M4 12c2 0 2 5 5 5s3-5 5-5 2 5 5 5" stroke="url(#lg2)" strokeWidth="2" strokeLinecap="round" opacity="0.55"/><defs><linearGradient id="lg1" x1="4" y1="7" x2="19" y2="7"><stop stopColor="#818cf8"/><stop offset="1" stopColor="#22d3ee"/></linearGradient><linearGradient id="lg2" x1="4" y1="17" x2="19" y2="17"><stop stopColor="#34d399"/><stop offset="1" stopColor="#22d3ee"/></linearGradient></defs></svg><span className="tf-logo-word">TraceFlow</span></span>); }
function NavBar() { const [scrolled, setScrolled] = useState(false); const [open, setOpen] = useState(false); const [action,setaction]=useState(); useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 12); window.addEventListener("scroll", onScroll); return () => window.removeEventListener("scroll", onScroll); }, []); const links = ["Product", "Pricing", "Docs"]; const linked=[{name:"product",path:"#"},{name:"Pricing",path:"#"},{name:"Docs",path:"../traceflow-docs"}]; return (<header className={`tf-nav ${scrolled ? "tf-nav-scrolled" : ""}`}><div className="tf-nav-inner"><Logo/><nav className="tf-nav-links">{linked.map((l) => (<a key={l.name} href={l.path} className="tf-nav-link">{l.name}</a>))}</nav><div className="tf-nav-actions"><Link href="/login" className="tf-nav-link tf-nav-login">Log in</Link><button className="tf-btn tf-btn-ghost">Dashboard</button><Link href="/register" className="tf-btn tf-btn-solid" style={{ color: "#05070d" }}>Get started</Link></div><button className="tf-nav-burger" onClick={() => setOpen((o) => !o)} aria-label="Menu"><span/><span/><span/></button></div>{open && (<div className="tf-nav-mobile">{links.map((l) => (<a key={l} href="#">{l}</a>))}<button className="tf-btn tf-btn-solid" style={{ width: "100%" }}>Get started</button></div>)}</header>); }
const HERO_NODES = [{ id:"client",x:60,y:150,label:"client",ms:null },{ id:"gateway",x:210,y:60,label:"gateway",ms:4 },{ id:"auth",x:210,y:240,label:"auth-svc",ms:8 },{ id:"orders",x:380,y:30,label:"orders-svc",ms:22 },{ id:"billing",x:380,y:130,label:"billing-svc",ms:41 },{ id:"inventory",x:380,y:230,label:"inventory-svc",ms:17 },{ id:"db",x:380,y:300,label:"postgres",ms:63 }];
const HERO_EDGES = [["client","gateway"],["client","auth"],["gateway","orders"],["gateway","billing"],["auth","inventory"],["billing","db"],["inventory","db"]];
function HeroGraph() { const [active,setActive]=useState(0); useEffect(()=>{const id=setInterval(()=>setActive(a=>(a+1)%HERO_EDGES.length),900);return()=>clearInterval(id)},[]); const find=(id)=>HERO_NODES.find(n=>n.id===id); return (<div className="tf-hero-graph"><svg viewBox="0 0 460 330" className="tf-hero-svg">{HERO_EDGES.map(([a,b],i)=>{const A=find(a);const B=find(b);const isActive=i===active;return <line key={i} x1={A.x} y1={A.y} x2={B.x} y2={B.y} className={`tf-edge ${isActive?"tf-edge-active":""}`}/>})}{HERO_EDGES.map(([a,b],i)=>{if(i!==active)return null;const A=find(a);const B=find(b);return <circle key={"p"+i} r="3.5" className="tf-pulse-dot"><animate attributeName="cx" values={`${A.x};${B.x}`} dur="0.85s" fill="freeze"/><animate attributeName="cy" values={`${A.y};${B.y}`} dur="0.85s" fill="freeze"/></circle>})}{HERO_NODES.map(n=>(<g key={n.id} transform={`translate(${n.x},${n.y})`} className="tf-node-g"><circle r="15" className="tf-node-ring"/><circle r="5.5" className="tf-node-core"/><text y="-24" textAnchor="middle" className="tf-node-label">{n.label}</text>{n.ms&&<text y="30" textAnchor="middle" className="tf-node-ms">{n.ms}ms</text>}</g>))}</svg><div className="tf-hero-graph-footer"><span className="tf-live-dot"/> live trace &middot; req_8f2a19c</div></div>); }
function Hero(){return <section className="tf-hero"><div className="tf-grid-bg"/><div className="tf-noise"/><div className="tf-glow tf-glow-a"/><div className="tf-glow tf-glow-b"/><div className="tf-hero-inner"><Reveal className="tf-eyebrow"><Sparkles size={13}/> now tracing 50M+ requests a day</Reveal><Reveal delay={80}><h1 className="tf-h1">See every request,<br/><span className="tf-h1-accent">before it becomes an incident.</span></h1></Reveal><Reveal delay={160}><p className="tf-hero-sub">TraceFlow is distributed tracing built for backend teams — follow a request across every service, span, and query, and know exactly where your latency lives.</p></Reveal><Reveal delay={240} className="tf-hero-ctas"><button className="tf-btn tf-btn-solid tf-btn-lg">Start tracing free <ArrowRight size={16}/></button><button className="tf-btn tf-btn-outline tf-btn-lg"><TerminalIcon size={15}/> npx traceflow init</button></Reveal><Reveal delay={340} className="tf-hero-visual"><HeroGraph/></Reveal></div></section>}
const STAGES=[{label:"Client",detail:"browser / mobile / cli",ms:0},{label:"API Gateway",detail:"routing + rate limits",ms:4},{label:"Authentication",detail:"token verification",ms:9},{label:"Business Logic",detail:"orders-svc handler",ms:26},{label:"Database",detail:"postgres query",ms:54},{label:"Trace Storage",detail:"span ingest",ms:61},{label:"Dashboard",detail:"rendered + alertable",ms:66}];
function HowItWorks(){const [active,setActive]=useState(0);const [ref,visible]=useReveal(0.3);useEffect(()=>{if(!visible)return;const id=setInterval(()=>setActive(a=>(a+1)%STAGES.length),1100);return()=>clearInterval(id)},[visible]);return <section className="tf-section" ref={ref}><Reveal className="tf-section-head"><span className="tf-eyebrow">the request lifecycle</span><h2 className="tf-h2">One request, seven hops, zero blind spots</h2><p className="tf-section-sub">Every stage below is a real span TraceFlow captures automatically.</p></Reveal><div className="tf-pipeline"><div className="tf-pipeline-track"><div className="tf-pipeline-progress" style={{height:`${(active/(STAGES.length-1))*100}%`}}/><div className="tf-pipeline-dot" style={{top:`${(active/(STAGES.length-1))*100}%`}}/></div><ol className="tf-pipeline-list">{STAGES.map((s,i)=><li key={s.label} className={`tf-pipeline-item ${i===active?"tf-pipeline-active":""} ${i<active?"tf-pipeline-done":""}`}><div className="tf-pipeline-text"><span className="tf-pipeline-name">{s.label}</span><span className="tf-pipeline-detail">{s.detail}</span></div><span className="tf-pipeline-ms">+{s.ms}ms</span></li>)}</ol></div></section>}
function Features(){return <section className="tf-section"><Reveal className="tf-section-head"><span className="tf-eyebrow">capabilities</span><h2 className="tf-h2">Everything an on-call engineer actually opens</h2><p className="tf-section-sub">Six tools that share one trace model, so context never gets lost between them.</p></Reveal></section>}
function SdkExample(){return <section className="tf-section"><Reveal className="tf-section-head"><span className="tf-eyebrow">sdk</span><h2 className="tf-h2">One import, full instrumentation</h2></Reveal></section>}
function DashboardPreview(){return <section className="tf-section"><Reveal className="tf-section-head"><span className="tf-eyebrow">product</span><h2 className="tf-h2">A dashboard built around one trace, not one metric</h2></Reveal></section>}
const STATS=[{value:50,suffix:"M+",label:"Requests traced daily"},{value:99.99,suffix:"%",label:"SDK reliability",decimals:2},{value:5,suffix:"ms",label:"Average SDK overhead"},{value:500,suffix:"+",label:"Engineering teams"}];
function StatItem({s}){const [ref,visible]=useReveal(0.5);const value=useCountUp(s.value,1500,visible);return <div className="tf-stat" ref={ref}><div className="tf-stat-value">{s.decimals?value.toFixed(s.decimals):Math.round(value)}{s.suffix}</div><div className="tf-stat-label">{s.label}</div></div>}
function Stats(){return <section className="tf-section tf-stats-section"><div className="tf-stats-grid">{STATS.map(s=><StatItem s={s} key={s.label}/>)}</div></section>}
function Testimonials(){return <section className="tf-section"><Reveal className="tf-section-head"><span className="tf-eyebrow">from the field</span><h2 className="tf-h2">Teams debugging faster, not harder</h2></Reveal></section>}
function Pricing(){return <section className="tf-section"><Reveal className="tf-section-head"><span className="tf-eyebrow">pricing</span><h2 className="tf-h2">Priced for teams, not per-seat headaches</h2></Reveal></section>}
function Faq(){return <section className="tf-section"><Reveal className="tf-section-head"><span className="tf-eyebrow">faq</span><h2 className="tf-h2">Good to know</h2></Reveal></section>}
function Footer(){return <footer className="tf-footer"><div className="tf-footer-top"><div><Logo/><p className="tf-footer-tagline">Distributed tracing for backend teams who ship fast and debug faster.</p></div></div><div className="tf-footer-bottom"><span>© {new Date().getFullYear()} TraceFlow, Inc.</span></div></footer>}
export default function TraceFlowLanding(){return <div className="tf-root"><NavBar/><Hero/><Features/><HowItWorks/><SdkExample/><DashboardPreview/><Stats/><Testimonials/><Pricing/><Faq/><Footer/></div>}
